### ISSUE TITLE
Rename flap switch to better indicate 3-way functionality

### ISSUE THREAD

**Issue by Breadmaker91** [Breadmaker91/DCS-SK60-Mod#30]
Give flap switch binding following names:
Flaps Up else Takeoff
Flaps Landing else Takeoff

**Comment by CorsairCat** [comment]
Changed to the following
```
Flaps Up/Down (Warthunder like logic)
Flaps Move Down (One Step)
Flaps Move Up (One Step)
```

**Comment by Breadmaker91** [comment]
Flap command doesn't show up in Control settings
![Screen_221123_084730](https://user-images.githubusercontent.com/77408529/203494884-c85999d0-da67-42b3-8b39-d754d73bb196.jpg)

**Comment by CorsairCat** [comment]
![screenshot](https://user-images.githubusercontent.com/51845471/203637967-f4ab91f0-ce10-418e-a986-de819f2aed59.png)
its under the system and you can see here; can you check if you can see that (might be some issue with your self defined?
