### ISSUE TITLE
Hot start brakes altimiter knob & flood light knob (can only be rotated one way

### ISSUE THREAD

**Issue by Breadmaker91** [Breadmaker91/DCS-SK60-Mod#41]
### Subsystem:
Cockpit systems
### Expected Behavior:
Altimiter setting knob & flood lighting knob should be able to rotate both ways.
### Steps To Reproduce:
Spawn in hotstarted aircraft
Try to rotate the knob
### Additional info:

**Comment by CorsairCat** [comment]
doesnt happen on my testing

**Comment by Breadmaker91** [comment]
It doesn't happen every time for me either, but some times it does.
