### ISSUE TITLE
Is data collection system still active and how can I request my data be deleted?

### ISSUE THREAD

**Issue by Drofseh** [Breadmaker91/DCS-SK60-Mod#49]
Hello

In the public [v1.0.0](https://github.com/Breadmaker91/DCS-SK60-Mod/releases/tag/v1.0.0) release of this mod there is a [Privacy Statement](https://github.com/Breadmaker91/DCS-SK60-Mod/blob/v1.0.0/Docs/PrivacyStatement.md) document in the Docs folder that states that the IP and location of users is being collected.

Is this system still active in the v1.0.0 release, and if it is how can I request my collected data be deleted?

Thank you

**Comment by Breadmaker91** [comment]
There's no data collected. That document is from the closed beta testing. It will be removed in the next update. Thanks for pointing it out!

**Comment by Drofseh** [comment]
That's what I'd hoped, than you for confirming and congratulations on the release!
